name: publish extension to marketplace
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    name: Publish
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Publish
      if: success()
      run: |
        git config user.email "pavel.zybenkov@gmail.com"
        git config user.name "Github actions"
        cd Extension
        npm install
        npm run publish
        git diff
        git push
      env:
        VSCE_PAT: ${{ secrets.VSCETOKEN }}
    