name: publish extension to marketplace
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  publish:
    name: Publish
    if: github.event_name == 'workflow_dispatch'
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Publish
      if: success()
      run: |
        git config user.email "pavel.zybenkov@gmail.com"
        git config user.name "Github actions"
        git submodule update --init --recursive
        cd Extension
        npm install
        npm run publish -- 0.1.${{github.run_number}}
      env:
        VSCE_PAT: ${{ secrets.VSCETOKEN }}
  updateTemplates:
    name: Update Templates
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Templates submodule update
      if: success()
      run: |
        git config user.email "pavel.zybenkov@gmail.com"
        git config user.name "Github actions"
        git submodule update --remote --force
        git commit -a -m "templates updated"
        git push
      env:
        VSCE_PAT: ${{ secrets.VSCETOKEN }}