name: update project templates
on:
  repository_dispatch:
jobs:
  updateTemplates:
    name: Update Templates
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Templates submodule update
      if: success()
      run: |
        git config user.email "pavel.zybenkov@gmail.com"
        git config user.name "Github actions"
        git submodule update --init --recursive
        git submodule update --remote --force
        git commit -a -m "templates updated"
        git push
      env:
        VSCE_PAT: ${{ secrets.VSCETOKEN }}